name: Check ESLint Configuration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Compare .eslintrc.json file with expected config
      - name: Check ESLint config file
        run: |
          if ! diff -q .github/expected_eslintrc.json .eslintrc.json > /dev/null; then
            echo "Error: .eslintrc.json has been modified"
            exit 1
          fi

      # Check package.json for eslint-related fields
      - name: Check for ESLint config in package.json
        run: |
          if grep -q '"eslintConfig"' package.json; then
            echo "Error: eslintConfig found in package.json"
            exit 1
          fi

      # Check for ESLint config comments in files
      - name: Check for ESLint config comments
        run: |
          if grep -r --include=\*.js -E '(eslint-disable|eslint-enable|eslint-config)' .; then
            echo "Error: ESLint configuration comments found in source files"
            exit 1
          fi
